name: Pipeline - update-sfdc-accounts

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        custom_environment:
          description: 'Target Environment ("update_sfdc_prod", "update_sfdc_stage")'
          required: true
          default: "update_sfdc_prod"
  schedule:
    - cron: "0 9 * * *"

jobs:
  update-sfdc-accounts:
    name: update-sfdc-accounts
    runs-on: ubuntu-latest
    # pick the update_sfdc_prod environment if triggered off of cron schedule
    environment: ${{(github.event_name == 'workflow_dispatch') && inputs.custom_environment || 'update_sfdc_prod'}}
    env:
      SALESFORCE_CLIENT_ID: ${{secrets.SALESFORCE_CLIENT_ID}}
      SALESFORCE_CLIENT_SECRET: ${{secrets.SALESFORCE_CLIENT_SECRET}}
      SALESFORCE_USERNAME: ${{secrets.SALESFORCE_USERNAME}}
      SALESFORCE_PASSWORD: ${{secrets.SALESFORCE_PASSWORD}}
      SALESFORCE_SECURITY_TOKEN: ${{secrets.SALESFORCE_SECURITY_TOKEN}}
      SALESFORCE_HOST: ${{vars.SALESFORCE_HOST}}
      SNOWFLAKE_ACCOUNT: ${{vars.SNOWFLAKE_ACCOUNT}}
      SNOWFLAKE_SALESFORCE_USER: ${{vars.SNOWFLAKE_SALESFORCE_USER}}
      SNOWFLAKE_SALESFORCE_USER_PWD: ${{secrets.SNOWFLAKE_SALESFORCE_USER_PWD}}
      SNOWFLAKE_WAREHOUSE: ${{vars.SNOWFLAKE_WAREHOUSE}}
      SNOWFLAKE_SALESFORCE_ROLE: ${{vars.SNOWFLAKE_SALESFORCE_ROLE}}
      SALESFORCE_SNITCH_URL: ${{vars.SALESFORCE_SNITCH_URL}}

      BU_SLACK_BOT_TOKEN: ${{ secrets.BU_SLACK_BOT_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.DATA_SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      GITHUB_ACTION_URL: "https://github.com/betterup/betterup-analytics/actions/workflows/update_sfdc_accounts.yml"
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Setup poetry
        uses: snok/install-poetry@v1

      - name: Run update-sfdc-accounts job
        run: sudo chmod +x bin/update-sfdc-accounts && bin/update-sfdc-accounts
      
      - name: Send GitHub Action data to Slack workflow
        id: send-slack-notification
        uses: slackapi/slack-github-action@v1.23.0
        if: failure()
        with:
          payload: |
            {
              "channel": "warroom-data",
              "icon_emoji": ":github:",
              "text": "Pipeline Failure: ${{ github.workflow }} <${{ env.GITHUB_ACTION_URL }}|View here.>"
            }
